stages:
    - build_package
    - pdf_build
    - tests_coverage_publish
    #- unit_tests

build_package_job:
    stage: build_package
    tags:
    - docker
    image: maven:latest
    script:
    - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml clean package
    artifacts:
        paths:
            - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetProducer-jar-with-dependencies.jar
            - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetFilter-jar-with-dependencies.jar
            - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagExtractor-jar-with-dependencies.jar
            - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagCounter-jar-with-dependencies.jar

pages:
  stage: pdf_build
  tags:
    - docker
  script:
    - latexmk -pdf main.tex
    - mv main.pdf public/
  artifacts:
    paths:
      - public/
    expire_in: 1 month

tests_reports_job:
    stage: tests_reports
    tags:
    - docker
    image: maven:latest
    script:
    - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml verify
    artifacts:
        reports:
            junit:
            - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/surefire-reports/TEST-*.xml

pages:
    stage: tests_coverage_publish
    tags:
    - docker
    script:
    - mkdir -p public/testCoverageReport
    - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/site/jacoco/* public/testCoverageReport/
    only:
    - main
    artifacts:
        paths:
        - public/testCoverageReport