stages:
    #- upload_jar_artifacts
    - junit_tests
    - tests_coverage_publish
    - deploy_pages
    - build_package
    - create_docker_images

build_package_job:
    stage: build_package
    tags:
      - docker
    image: maven:latest
    script:
    - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml clean package
    # - ls 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/
    # - mkdir -p jar_artifacts
    # - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetProducer-jar-with-dependencies.jar jar_artifacts/
    # - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetFilter-jar-with-dependencies.jar jar_artifacts/
    # - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagExtractor-jar-with-dependencies.jar jar_artifacts/
    # - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagCounter-jar-with-dependencies.jar jar_artifacts/
  

# upload_tweet_producer:
#   stage: upload_jar_artifacts
#   dependencies:
#     - build_package_job
#   script:
#     - ls jar_artifacts/
#     - ls 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/
#     - echo "Uploading Tweet Producer artifact"
#   artifacts:
#     paths:
#       - jar_artifacts/TweetProducer-jar-with-dependencies.jar

# upload_tweet_filter:
#   stage: upload_jar_artifacts
#   dependencies:
#     - build_package_job
#   script:
#     - echo "Uploading Tweet Filter artifact"
#   artifacts:
#     paths:
#       - $CI_PROJECT_DIR/jar_artifacts/TweetFilter-jar-with-dependencies.jar

# upload_hashtag_extractor:
#   stage: upload_jar_artifacts
#   dependencies:
#     - build_package_job
#   script:
#     - echo "Uploading Hashtag Extractor artifact"
#   artifacts:
#     paths:
#       - jar_artifacts/HashtagExtractor-jar-with-dependencies.jar

# upload_hashtag_counter:
#   stage: upload_jar_artifacts
#   dependencies:
#     - build_package_job
#   script:
#     - echo "Uploading Hashtag Counter artifact"
#   artifacts:
#     paths:
#       - jar_artifacts/HashtagCounter-jar-with-dependencies.jar


unit_test_job:
  stage: junit_tests
  tags:
    - docker
  image: maven:latest
  script:
    - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml test


pages:
  stage: deploy_pages
  tags:
    - docker
  script:
    - apt-get update -qy
    - apt-get install -y perl
    - apt-get install -y latexmk
    - latexmk -pdf -f -interaction=nonstopmode main.tex
    - mkdir -p public/MainReport
    - mv main.pdf public/MainReport
  artifacts:
    paths:
      - public/MainReport

tests_reports_job:
    stage: tests_coverage_publish
    tags:
    - docker
    image: maven:latest
    script:
    - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml clean verify jacoco:report
    artifacts:
        reports:
            junit:
            - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/surefire-reports/TEST-*.xml
        paths:
          - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/site/jacoco

pages:
    stage: deploy_pages
    tags:
     - docker
    dependencies:
      - tests_reports_job
    script:
     #- ls -R 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target
     - mkdir -p public/testCoverageReport
     - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/site/jacoco/* public/testCoverageReport
    artifacts:
        paths:
        - public/testCoverageReport 

create_proxy_docker_image_job:
    stage: create_docker_images
    tags:
        - docker
    image: 
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint: [""]
    script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/docker_files/Dockerfile.filterForKubernetes" --destination "${CI_REGISTRY}/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/filterForKubernetes:latest" --cleanup
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/docker_files/Dockerfile.hashtagCounterForKubernetes" --destination "${CI_REGISTRY}/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/hashtagCounterForKubernetes:latest" --cleanup
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/docker_files/Dockerfile.hashtagExtractorForKubernetes" --destination "${CI_REGISTRY}/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/hashtagExtractorForKubernetes:latest" --cleanup
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/docker_files/Dockerfile.mockForKubernetes" --destination "${CI_REGISTRY}/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/mockForKubernetes:latest" --cleanup