stages:
    - build_package
    - upload_jar_artifacts
    - pdf_build
    - tests_coverage_publish
    #- unit_tests

build_package_job:
    stage: build_package
    tags:
    - docker
    image: maven:latest
    script:
    - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml clean package
    # All 4 .jar files seem to be to big for a job. And I can't find in the gitlab the setting to make it bigger...
    # artifacts:
    #     paths:
    #         - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetProducer-jar-with-dependencies.jar
    #         - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetFilter-jar-with-dependencies.jar
    #         - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagExtractor-jar-with-dependencies.jar
    #         - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagCounter-jar-with-dependencies.jar
  
upload_tweet_producer:
  stage: upload_jar_artifacts
  dependencies:
    - build_package_job
  script:
    - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetProducer-jar-with-dependencies.jar tweet_producer.jar
    - echo "Uploading Tweet Producer artifact"
  artifacts:
    paths:
      - jar_artifacts/tweet_producer.jar

upload_tweet_filter:
  stage: upload_jar_artifacts
  dependencies:
    - build_package_job
  script:
    - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/TweetFilter-jar-with-dependencies.jar tweet_filter.jar
    - echo "Uploading Tweet Filter artifact"
  artifacts:
    paths:
      - jar_artifacts/tweet_filter.jar

upload_hashtag_extractor:
  stage: upload_jar_artifacts
  dependencies:
    - build_package_job
  script:
    - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagExtractor-jar-with-dependencies.jar hashtag_extractor.jar
    - echo "Uploading Hashtag Extractor artifact"
  artifacts:
    paths:
      - jar_artifacts/hashtag_extractor.jar

upload_hashtag_counter:
  stage: upload_jar_artifacts
  dependencies:
    - build_package_job
  script:
    - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/HashtagCounter-jar-with-dependencies.jar hashtag_counter.jar
    - echo "Uploading Hashtag Counter artifact"
  artifacts:
    paths:
      - jar_artifacts/hashtag_counter.jar

pages:
  stage: pdf_build
  tags:
    - docker
  script:
    - latexmk -pdf main.tex
    - mv main.pdf public/
  artifacts:
    paths:
      - public/

# tests_reports_job:
#     stage: tests_reports
#     tags:
#     - docker
#     image: maven:latest
#     script:
#     - mvn -f 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/pom.xml verify
#     artifacts:
#         reports:
#             junit:
#             - 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/surefire-reports/TEST-*.xml

pages:
    stage: tests_coverage_publish
    tags:
    - docker
    script:
    - mkdir -p public/testCoverageReport
    - mv 3MD1510_IAL-main-Tweetoscope/Tweetoscope/InitialTweetoscope/target/site/jacoco/* public/testCoverageReport/
    # only:
    # - main
    artifacts:
        paths:
        - public/testCoverageReport