version: '3.9'

services:
  mock:
    build: 
      context: ./
      dockerfile: docker_files/Dockerfile.mockForKubernetes
    environment:
        - PRODUCER_NAME=$PRODUCER_NAME
        - RECORDED_OPTION=$RECORDED_OPTION

  filter:
    build:
      context: ./
      dockerfile: docker_files/Dockerfile.filterForKubernetes
    environment:
      - FILTER_NAME=$FILTER_NAME
      - FILTER_OPTION=$FILTER_OPTION
      
  hashtag-counter:
    build: 
      context: ./
      dockerfile: docker_files/Dockerfile.hashtagCounterForKubernetes
    environment:
      - NBLEADERS=$NBLEADERS

  hashtag-extractor:
    build: 
      context: ./
      dockerfile: docker_files/Dockerfile.hashtagExtractorForKubernetes

