apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: ial-34-ns
spec:
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    targetPort: 2181
    port: 2181
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-pod
  namespace: ial-34-ns
  labels:
    app: zookeeper
spec:
  containers:
  - name: zookeeper-container
    image: zookeeper
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
  namespace: ial-34-ns
spec:
  selector:
    app: kafka-broker
  ports:
  - protocol: TCP
    targetPort: 9092
    port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
  namespace: ial-34-ns
spec:
  selector:
    app: kafka-broker
  ports:
  - protocol: TCP
    targetPort: 9093
    port: 9093
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  namespace: ial-34-ns
  labels:
    app: kafka-broker
spec:
  containers:
  - name: kafka-container
    image: wurstmeister/kafka
    imagePullPolicy: IfNotPresent
    env:
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafka
    - name: KAFKA_CREATE_TOPICS
      value: "tweets:1:1,filtered_tweet:1:1,hashtags:1:1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper-service:2181"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT,PLAINTEXT2:PLAINTEXT"
    - name: KAFKA_LISTENER_PLAINTEXT_LISTENER_NAME
      value: "PLAINTEXT"
    - name: KAFKA_LISTENER_PLAINTEXT_LISTENER_PORT
      value: "9092"
    - name: KAFKA_LISTENER_PLAINTEXT2_LISTENER_NAME
      value: "PLAINTEXT2"
    - name: KAFKA_LISTENER_PLAINTEXT2_LISTENER_PORT
      value: "9093"

