apiVersion: v1
kind: Pod
metadata:
  name: mock-pod
  namespace: ial-34-ns
spec:
  containers:
  - name: mock-container
    image: gitlab-student.centralesupelec.fr:4567/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/mockforkubernetes:latest
    imagePullPolicy: Always
    env:
    - name: PRODUCER_NAME
      value: "random"
---
apiVersion: v1
kind: Pod
metadata:
  name: filter-pod
  namespace: ial-34-ns
spec:
  containers:
  - name: filter-container
    image: gitlab-student.centralesupelec.fr:4567/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/filterforkubernetes:latest
    imagePullPolicy: Always
    env:
    - name: FILTER_NAME
      value: "empty"
---
apiVersion: v1
kind: Pod
metadata:
  name: hashtagextractor-pod
  namespace: ial-34-ns
spec:
  containers:
  - name: hashtagextractor-container
    image: gitlab-student.centralesupelec.fr:4567/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/hashtagextractorforkubernetes:latest
    imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: hashtagcounter-pod
  namespace: ial-34-ns
spec:
  containers:
  - name: hashtagcounter-container
    image: gitlab-student.centralesupelec.fr:4567/julien.michel/tweetoscope23_group-02_broderick_hazard_michel/hashtagcounterforkubernetes:latest
    imagePullPolicy: Always
    env:
    - name: NBLEADERS
      value: "10"

